### PR TITLE
Remove unused dependency properties-parser

### PR DESCRIPTION
**Pull request by raphinesse**
Was not found earlier, since it is "used" in our test fixtures.

### CODE REVIEW

**Comment by ath0mas** [comment]
I'm using cordova/cordova-lib in a nodejs project and since update from cordova 7 to 9 I have an error calling `cordova.prepare()`:
(to have more logs I called it using `npx cordova prepare`)
```
$ npx cordova prepare
npx: installed 453 in 12.921s
Unable to load PlatformApi from platform. Error: Cannot find module 'properties-parser'
Require stack:
- /usr/src/geomobile/geomobile-build/build/dev/platforms/android/cordova/lib/AndroidProject.js
- /usr/src/geomobile/geomobile-build/build/dev/platforms/android/cordova/Api.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/src/help.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/src/cli.js
- /home/jenkins/.npm/_npx/4088/lib/node_modules/cordova/bin/cordova
Unhandled error. ('The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.')
```
so maybe *properties-parser* was useful?
